export const prodConfig = {
  name: 'prod',
  baseUrl: 'https://commerce.koosco.co.kr',
  authService: 'https://commerce.koosco.co.kr',
  userService: 'https://commerce.koosco.co.kr',
  catalogService: 'https://commerce.koosco.co.kr',
  inventoryService: 'https://commerce.koosco.co.kr',
  orderService: 'https://commerce.koosco.co.kr',
  paymentService: 'https://commerce.koosco.co.kr',
  paths: {
    auth: '/api/auth',
    users: '/api/users',
    products: '/api/products',
    categories: '/api/categories',
    inventory: '/api/inventories',
    orders: '/api/orders',
    payments: '/api/payments',
  },
  rateLimit: 100,
};
